const ROOM_ID_LENGHT = 7;

const STATUS_DELAY = 3000;
const REMATCH_WINDOW = 10000;
const RESERVATION_EXPIRY = 30000;
const CLEANUP_GRACE_PERIOD = 10000;

export { ROOM_ID_LENGHT, STATUS_DELAY, REMATCH_WINDOW, RESERVATION_EXPIRY, CLEANUP_GRACE_PERIOD };
